### ISSUE TITLE
Is there a work around accessing us_privacy string when CCPA & GPP are enabled 

### ISSUE THREAD

**Issue by acamara2016** [InteractiveAdvertisingBureau/USPrivacy#23]
In your sdk, inside the function `function convertIABGPPKeys()` 
it's removing US Privacy string from global variables and US Privacy string from registry.

This is causing an issue with how our app is currently set and expected us_privacy when GPP and CCPA are enabled, is there is a work around on the Privacy side on how you have set up One Trust?

**Comment by patmmccann** [comment]
you should probably post on the sdk repo, not sure which sdk you are referring to but it might be this one https://github.com/IABTechLab/iabgpp-java or https://github.com/IABTechLab/iabgpp-es

the repo maintainers on this repo aren't even merging typo fixes (https://github.com/InteractiveAdvertisingBureau/USPrivacy/pulls)

**Comment by acamara2016** [comment]
Thanks @patmmccann, we actually found a work around this on player side. I will close the issue.
